language: go

go:
    - 1.2
    - 1.3
    - 1.4
    - 1.5
    - 1.6
    - tip

before_install:
    - sudo apt-get install tesseract-ocr
before_script:
    - go get github.com/otiai10/mint
script:
    - go test -v ./...
